# Generated By Create New Playground (lmao) #
# Generated At: 2025-12-11 22:19:08.122714
# Author: Zane Reisbig

import unittest
import pathlib
from time import sleep

###
from WaveFrontDOTPy import WaveObj, TokenConsumers, UnknownTagException
from WaveFrontDOTPy.Object import decode

###

OBJECT_FOLDER_PATH = pathlib.Path("./object/").absolute()

SELECTED_TEST_CASE = 2
TEST_OBJECTS = [
    pathlib.Path("Joe_Cube.obj"),
    pathlib.Path("Space_In_Material.obj"),
    pathlib.Path("Many_Materials.obj"),
    pathlib.Path("WusonOBJ.obj"),
]

OUT_FILE_PATH = pathlib.Path(OBJECT_FOLDER_PATH, "outObject").absolute()


TEST_CASE_PATH = pathlib.Path(
    OBJECT_FOLDER_PATH, TEST_OBJECTS[SELECTED_TEST_CASE]
).absolute()


def getTestObjFile():
    lines: list[str] | None = None
    with open(str(TEST_CASE_PATH)) as file:
        lines = file.readlines()

    return lines


class All(unittest.TestCase):

    def test_canGetRawObjFile(self):
        fileLines = getTestObjFile()

        self.assertIsNotNone(fileLines)

    def test_canDetectHasTag(self):
        tag = "v 0.120 0.234 0.345"

        tagless = TokenConsumers.consumeTagAndReturnLeftover(tag)
        self.assertFalse("v" in tagless)

        shouldFail = None
        with self.assertRaises(UnknownTagException) as exceptionSlot:
            shouldFail = TokenConsumers.consumeTagAndReturnLeftover(tagless)

        self.assertIn("REASON", str(exceptionSlot.exception))
        self.assertIsNone(shouldFail)

    def test_canDecodeWholeFile(self):
        objects = decode(TEST_CASE_PATH)

        self.assertGreater(len(objects), 0)

        # for obj in objects:
        #     self.assertGreater(len(obj.verticies), 0)
        #     self.assertGreater(len(obj.vertexNormals), 0)
        #     self.assertGreater(len(obj.vertexTextures), 0)
        #     self.assertGreater(len(obj.faces.indexers), 0)

    def test_canExportIndividualObjects(self):
        objects = decode(TEST_CASE_PATH)
        self.assertGreater(len(objects), 0)

        objects[0].export(OUT_FILE_PATH)
